# Generated by Django 2.0.2 on 2018-03-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20180324_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='down_cloth_color',
            field=models.CharField(default='black', max_length=100),
        ),
    ]
