# Generated by Django 2.0.2 on 2018-03-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_object_down_cloth_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='interval',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
