# Generated by Django 2.0.2 on 2018-03-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_video_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='create_date',
            field=models.DateField(db_column='create_date'),
        ),
    ]
