# Generated by Django 2.0.2 on 2018-04-01 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20180328_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='camera_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysite.Video'),
        ),
    ]
