# Generated by Django 2.0.2 on 2018-04-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_video_hassummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='down_cloth_color_confidence',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='object',
            name='sex_confidence',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='object',
            name='upper_cloth_color_confidence',
            field=models.CharField(default=0.0, max_length=100),
        ),
    ]
