# Generated by Django 2.0.2 on 2018-04-02 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20180402_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='camera',
            new_name='camera_id',
        ),
    ]
